config/routes.rb
RemindavaxPilot::Application.routes.draw do

  match '/prepare_reminders', :to => 'patients#prepare_reminders', :via => :get
  match '/send_reminders', :to => 'patients#send_reminders', :via => :post

  resources :patients do
    collection do
      get 'autocomplete'
      get 'today'
    end
    member do
      post 'check_in'
      resources :appointments
    end
  end
  resources :tb_patients do
    member do
      resources :treatments
    end
  end
  resources :users
  resources :sessions
  resources :phcs do
    resources :subcenters, :only => [:new, :create, :index]
    collection do
      get 'summary'
    end
  end
  resources :anms
  resources :ashas
  resources :subcenters, :only => [:show, :destroy]

  root :to => redirect('/patients/today')
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/become_user', :to => 'sessions#become_user'
  match '/search', :to => 'patients#search'
  match '/search_tb', :to => 'tb_patients#search'

  post '/appointments/batch_update_dates'

  get '/cron/anm_sms'

  match '/summary', :to => 'phcs#summary'
  

end

app/models/asha.rb
# == Schema Information
# Schema version: 20110630040231
#
# Table name: ashas
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  mobile     :string(255)
#  phc_id     :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

class Asha < ActiveRecord::Base
  attr_accessible :name, :mobile

  belongs_to :phc
  validates :phc, :presence => true
  has_many :patients

  validates :name, :presence => true
  validates :mobile, :numericality => true, :length => { :is => 10, :message => "should be 10 digits"}, :allow_blank => true

  # This method should be called by a cron routine daily at 7:30AM IST, or
  # 2PM UTC/GMT, or 10PM EST
  def self.send_daily_reminders(send = true)
    messages = ""
    all.each do |asha|
      msg = asha.sms_message
      SmsHelper::send_sms(asha.mobile, msg) if send

      messages += "#{msg}\n"
    end

    logger.info "ASHA messages sent at #{Time.now}"
    logger.info messages
    messages
  end

  def sms_message
    msg = "#{name}- Today: "
    today = find_appointments_by_date(:date => Date.today).map do |a|
      p = a.patient
      "#{p.name} for #{a.name}, #{p.taayi_card_number}"
    end.join("; ")
    msg += (today.empty?) ? "None" : today

    msg += " -- Late: "
    # More than 3 days ago
    overdue = find_appointments_by_date(:before => 2.days.ago.to_date).map do |a|
      p = a.patient
      "#{p.name} for #{a.name}, #{p.taayi_card_number}"
    end.join("; ")
    msg += (overdue.empty?) ? "None" : overdue
    msg
  end

  def patients_due_today
    patients.select(&:appointment_today?)
  end

  def find_appointments_by_date(options)
    query = Appointment.includes(:patient).joins(:patient)
      .where("appointments.date > (SELECT MAX(date) FROM visits WHERE visits.patient_id = patients.id) OR (SELECT COUNT(1) FROM visits WHERE visits.patient_id = patients.id) = 0") # Ensure that 1) The latest visit was before the appointment OR 2) There have been no visits yet
      .where("patients.phc_id = ? AND patients.asha_id = ?", phc.id, id)
    if options[:date]
      query = query.where("appointments.date = ?", options[:date])
    end
    if options[:after]
      query = query.where("appointments.date > ?", options[:after])
    end
    if options[:before]
      query = query.where("appointments.date < ?", options[:before])
    end
    query
  end
end

app/controllers/ashas_controller.rb
class AshasController < ApplicationController
  before_filter :authorize, :only => [:show, :edit, :update, :destroy]

  def index
    @ashas = current_user.phc.ashas
  end

  def show
  end

  def new
    @asha = Asha.new
  end

  def create
    @asha = current_user.phc.ashas.build(params[:asha])
    if @asha.save
      flash[:success] = "Created a new ASHA!"
      redirect_to ashas_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @asha.update_attributes(params[:asha])
      flash[:success] = "Updated ASHA!"
      redirect_to ashas_path
    else
      render :edit
    end
  end

  def destroy
    @asha.destroy if @asha
    flash[:success] = "Successfully deleted #{@asha.name}"
    redirect_to ashas_path
  end

  private
    def authorize
      @asha = Asha.find_by_id(params[:id])
      unless @asha && @asha.phc.id == current_user.phc.id
        flash[:error] = "You do not have access to this ASHA"
        redirect_to ashas_path
      end
    end
end

app/views/ashas/_form.html.erb
<%= semantic_form_for @asha do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :mobile %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>

app/views/ashas/edit.html.erb
<h2>Edit ASHA</h2>
<%= render :partial => 'form' %>

app/views/ashas/index.html.erb
<h2>ASHAs</h2>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Mobile</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @ashas.each do |asha| %>
      <tr>
        <td><%= link_to asha.name, asha %></td>
        <td><%= asha.mobile %></td>
        <td><%= link_to "Edit", edit_asha_path(asha) %></td>
        <td><%= link_to "Delete", asha, :method => :delete, :confirm => "Are you sure you want to delete this ASHAk?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ashas/new.html.erb
<h2>New ASHA</h2>
<%= render :partial => 'form' %>

app/views/ashas/show.html.erb
<h1><%= @asha.name %></h1>

<ul>
  <li><b>Mobile:</b> <%= @asha.mobile %></li>
</ul>

<h3>Patients</h3>
<ul>
  <% @asha.patients.each do |p| %>
    <li><%= link_to p.name, p %></li>
  <% end %>
</ul>