config/routes.rb
RemindavaxPilot::Application.routes.draw do

  match '/prepare_reminders', :to => 'patients#prepare_reminders', :via => :get
  match '/send_reminders', :to => 'patients#send_reminders', :via => :post

  resources :patients do
    collection do
      get 'autocomplete'
      get 'today'
    end
    member do
      post 'check_in'
      resources :appointments
    end
  end
  resources :tb_patients do
    member do
      resources :treatments
    end
  end
  resources :users
  resources :sessions
  resources :phcs do
    resources :subcenters, :only => [:new, :create, :index]
    collection do
      get 'summary'
    end
  end
  resources :anms
  resources :ashas
  resources :subcenters, :only => [:show, :destroy]

  root :to => redirect('/patients/today')
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/become_user', :to => 'sessions#become_user'
  match '/search', :to => 'patients#search'
  match '/search_tb', :to => 'tb_patients#search'

  post '/appointments/batch_update_dates'

  get '/cron/anm_sms'

  match '/summary', :to => 'phcs#summary'
  

end

app/models/tb_patient.rb
class TbPatient < ActiveRecord::Base
  attr_accessible :name, :age, :sex, :address, :mobile, :village, :subcenter_id,
    :anm_id, :caste, :children_below_6, :education

  belongs_to :phc
  validates :phc, :presence => true
  belongs_to :subcenter
  validates :subcenter, :presence => true
  belongs_to :anm
  validates :anm, :presence => true
  has_many :visits#, :dependent => :destroy
  has_many :appointments#, :dependent => :destroy
  has_many :treatments, :dependent => :destroy
  has_many :sms
  
  belongs_to :subcenter
  belongs_to :anm

  validates :name, :presence => true
  validates :age, :presence => true, :numericality => true
  validates :sex, :presence => true
  enumerate :sex do
    value :name => 'male'
    value :name => 'female'
  end
  validates :address, :presence => true
  validates :mobile, :presence => true, :numericality => true
  validates_length_of :mobile, :is => 10 , :message => "should be 10 digits"
  validates :village, :presence => true
  validates :subcenter, :presence => true
  validates :anm, :presence => true
  validates :caste, :presence => true
  enumerate :caste do
    value :name => 'SC'
    value :name => 'ST'
    value :name => 'Other'
  end
  validates :children_below_6, :presence => true
  enumerate :children_below_6 do
    value :name => 'yes'
    value :name => 'no'
  end
  enumerate :education do
    value :name => 'Illiterate'
    value :name => 'Literate'
    value :name => 'Primary Education'
    value :name => 'High School'
    value :name => 'Degree'
    value :name => 'Other'
  end
  
  # Note: attr_encrypted _must_ go after enumerate (active_enum) in order to
  # work.
  attr_encrypted :age, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :sex, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :address, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :mobile, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :village, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :caste, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :children_below_6, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :education, :key => APP_CONFIG['encrypt_key']
  
  def self.search(phc, query)
    where('phc_id = ? AND name LIKE ?', phc, "%#{query}%")
  end

  def previous_treatments
    treatments.select { |t| t.end_date < Date.today}
  end

  def ongoing_treatments
    treatments.select { |t| t.start_date <= Date.today &&
                            t.end_date >= Date.today}
  end

  def future_treatments
    treatments.select { |t| t.start_date > Date.today}
  end


  # This method should be called by a cron routine every Monday at 7:30AM IST, or
  # 2PM UTC/GMT, or 10PM EST
  def self.send_weekly_reminders(send = true)
    messages = ""
    all.each do |tb_patient|
      msg = "#{tb_patient.name}: "
      tb_patient.ongoing_treatments.each do |ongoing_treatment|
        if ongoing_treatment.frequency == 'weekly' then
          #create a message
          msg += "#{ongoing_treatment.message}\n"
        end
      end
        SmsHelper::send_sms(tb_patient.mobile, msg) if send
        messages += "#{msg}\n"
    end

    logger.info "TB Patient (continuous phase) messages sent at #{Time.now}"
    logger.info messages
    messages
  end

  # This method should be called by a cron routine every Monday, Wednesday, and Friday
  # at 7:30AM IST, or 2PM UTC/GMT, or 10PM EST
  def self.send_triweekly_reminders(send = true)
    messages = ""
    all.each do |tb_patient|
      msg = "#{tb_patient.name}: "
      tb_patient.ongoing_treatments.each do |ongoing_treatment|
        if ongoing_treatment.frequency == 'triweekly' then
          #create a message
          msg += "#{ongoing_treatment.message}\n"
        end
      end
        SmsHelper::send_sms(tb_patient.mobile, msg) if send
        messages += "#{msg}\n"
    end

    logger.info "TB Patient (intensive phase) messages sent at #{Time.now}"
    logger.info messages
    messages
  end

=begin
  def sms_message
    msg = "#{name}- Today: "

    today = find_appointments_by_date(:date => Date.today).map do |a|
      p = a.patient
      "#{p.name} for #{a.name}, #{p.taayi_card_number}"
    end.join("; ")

    msg += (today.empty?) ? "None" : today
    msg
  end
=end


end

app/controllers/tb_patients_controller.rb
class TbPatientsController < ApplicationController
  before_filter :authorize, :only => [:show, :edit, :update, :destroy, :check_in]

  def index
    @tb_patients = current_user.phc.tb_patients.order("name ASC").paginate(:page => params[:page])
  end

  def show
    #@visit = @tb_patient.latest_visit
    @ongoing_treatments = @tb_patient.ongoing_treatments
    @previous_treatments = @tb_patient.previous_treatments
    @future_treatments = @tb_patient.future_treatments
    @treatment = Treatment.new
  end

  def new
    @tb_patient = TbPatient.new
  end

  def create
    @phc = current_user.phc
    @tb_patient = @phc.tb_patients.build(params[:tb_patient])
    if @tb_patient.save
      flash[:success] = "Created a new registration!"
      redirect_to @tb_patient
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tb_patient.update_attributes(params[:tb_patient])
      flash[:success] = 'Updated registration!'
      redirect_to @tb_patient
    else
      render :edit
    end
  end

  def destroy
    @tb_patient.destroy if @tb_patient
    flash[:success] = "Successfully deleted registration"
    flash[:success] += " #{@tb_patient.name}" if @tb_patient
    redirect_to tb_patients_path
  end

  def search
    if params[:q] # A query was actually entered
        @tb_patients = TbPatient.search(current_user.phc, params[:q]).order("name ASC").paginate(:page => params[:page])
        if @tb_patients.any?
          render :index
        else
          @tb_patient = TbPatient.new(:name => params[:q])
          render :new
        end
    else # Just rerender the search page if nothing was entered
      render :search
    end
  end

=begin
  def check_in
    if not @patient.checked_in?
      @patient.visits.create!(:date => Date.today, :description => params[:description])
    end
    respond_to do |format|
      format.html { redirect_to @patient }
      format.js
    end
  end

=end
  def autocomplete
    @tb_patients = TbPatient.search(current_user.phc, params[:term]).order("name ASC").map(&:name)
    respond_to do |format|
      format.json { render :json => @tb_patients }
    end
  end
=begin

  def today
    # Yesterday and today
    @appts_today = current_user.phc
      .find_appointments_by_date(:after => 2.days.ago.to_date, :before => Date.tomorrow)
      .order("date ASC")
    # More than 2 days ago
    @overdue_appts = current_user.phc
      .find_appointments_by_date(:before => 1.day.ago.to_date)
      .order("date ASC")
  end

  def prepare_reminders
    get_reminders
  end

  def send_reminders
    appts = Appointment.find(params[:appointments])
    appts.each do |a|
      send_reminder(a) unless a.patient.subcenter.control?
    end
    flash[:success] = "Successfully sent #{appts.length} reminders!"
    redirect_to patients_path
  end

=end
  private
    def authorize
      @tb_patient = TbPatient.find(params[:id])
      unless @tb_patient && @tb_patient.phc.id == current_user.phc.id
        flash[:error] = "You do not have access to this patient"
        redirect_to tb_patients_path
      end
    end
=begin

    def get_reminders
      # Remind delivery appointments 2 weeks in advance
      @advance_reminders = current_user.phc.find_appointments_by_date(:date => 2.weeks.from_now.to_date).order("date ASC").select do |appt|
        appt.appointment_type.appointment_type_id == 4
      end
      @advance_reminders += current_user.phc.find_appointments_by_date(:date => 3.days.from_now.to_date).order("date ASC")
      @reminders = current_user.phc.find_appointments_by_date(:date => 1.day.from_now.to_date).order("date ASC")
      @alerts = current_user.phc.find_appointments_by_date(:before => 2.days.ago.to_date).order("date ASC")
    end
=end
end

app/views/tb_patients/_form.html.erb
<%= semantic_form_for @tb_patient do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :age %>
    <%= form.input :sex %>
    <%= form.input :address %>
    <%= form.input :mobile %>
    <%= form.input :village %>
    <%= form.input :subcenter, :collection => current_user.phc.subcenters.order("name ASC") %>
    <%= form.input :anm, :collection => current_user.phc.anms.order("name ASC") %>
    <%= form.input :caste %>
    <%= form.input :children_below_6 %>
    <%= form.input :education %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button :label => (@tb_patient.new_record?) ? 'Create Registration' : 'Update Registration' %>
  <% end %>
<% end %>

app/views/tb_patients/_search_form.html.erb
<%= form_tag search_tb_path, :method => :get, :id => "search_form" do %>
  <%= text_field_tag :q, params[:q], :placeholder => "Name", :autocomplete => "tb_patient" %>
  <%= submit_tag "Search!", :name => nil %>
<% end %>

app/views/tb_patients/_tb_search_form.html.erb
<%= form_tag search_tb_path, :method => :get, :id => "search_form" do %>
  <%= text_field_tag :q, params[:q], :placeholder => "Name", :autocomplete => "tb_patient" %>
  <%= submit_tag "Search!", :name => nil %>
<% end %>

app/views/tb_patients/edit.html.erb
<h2>Edit Registration</h2>
<%= render :partial => 'form' %>

app/views/tb_patients/index.html.erb
<%= render :partial => 'tb_search_form' %>
<h1>TB Registrations</h1>
<p class="subhead">If the registration you are looking for is not listed below, please add the registration <%= link_to "here", new_tb_patient_path %>.</p>

<%= will_paginate %>

<table id="tb_patients">
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Mobile</td>
      <td>Caste</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @tb_patients.each do |p| %>
      <tr>
        <td><%= link_to p.name, p %></td>
        <td><%= (p.subcenter.nil?) ? "None" : (link_to p.subcenter.name, p.subcenter) %></td>
        <td><%= p.mobile %></td>
        <td><%= TbPatient::Caste[p.caste.to_i] %></td>
        <td><%= link_to "Edit", edit_tb_patient_path(p) %></td>
        <td><%= link_to "Delete", p, :method => :delete, :confirm => "Are you sure you want to delete this registration?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<%= link_to "Add New TB Registration to Database", new_tb_patient_path, :id => "add_tb_patient" %>

app/views/tb_patients/new.html.erb
<h2>New TB Registration</h2>
<%= render :partial => 'form' %>

app/views/tb_patients/search.html.erb
<h1>Search</h1>
<p class="quiet">Please enter the name of your registration, or add a new registration <%= link_to "here", new_tb_patient_path %></p>
<%= render :partial => 'tb_search_form' %>

app/views/tb_patients/show.html.erb
<h1><%= @tb_patient.name %></h1>
<%= link_to "Edit", edit_tb_patient_path(@tb_patient) %>

<ul class="details">
  <li><b>Age:</b> <%= @tb_patient.age %></li>

  <li><b>Sex:</b> <%= TbPatient::Sex[@tb_patient.sex.to_i] %></li>

  <li><b>Address:</b> <%= @tb_patient.address %></li>
  <li><b>Mobile:</b> <%= @tb_patient.mobile %></li>
  <li><b>Village:</b> <%= @tb_patient.village %></li>
  <li><b>Subcenter:</b> <%= (@tb_patient.subcenter.nil?) ? "None" : (link_to @tb_patient.subcenter.name, @tb_patient.subcenter) %></li>
  <li><b>ANM:</b> <%= (@tb_patient.anm.nil?) ? "None" : (link_to @tb_patient.anm.name, @tb_patient.anm) %></li>
  <li><b>Caste:</b> <%= TbPatient::Caste[@tb_patient.caste.to_i] %></li>
  <li><b>Children below 6:</b> <%= TbPatient::ChildrenBelow6[@tb_patient.children_below_6.to_i] %></li>
  <li><b>Education:</b> <%= TbPatient::Education[@tb_patient.education.to_i] %></li>
</ul>

<h3>Previous Treatments</h3>
<% if @previous_treatments.any? %>
  <ul>
    <% @previous_treatments.each do |t| %>
      <li><%= t.name %> from <b><%= t.start_date %></b> to <b><%= t.end_date %></b> |
      <%= link_to "Delete", t, :method => :delete, :confirm => "Are you sure?" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No previous treatments!</p>
<% end %>

<h3>Ongoing Treatments</h3>
<% if @ongoing_treatments.any? %>
  <ul>
    <% @ongoing_treatments.each do |t| %>
      <li><%= t.name %> from <b><%= t.start_date %></b> to <b><%= t.end_date %></b> |
      <%= link_to "Delete", t, :method => :delete, :confirm => "Are you sure?" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No treatment are currently scheduled!</p>
<% end %>

<h3>Future Treatments</h3>
<% if @future_treatments.any? %>
  <ul>
    <% @future_treatments.each do |t| %>
      <li><%= t.name %> from <b><%= t.start_date %></b> to <b><%= t.end_date %></b> |
      <%= link_to "Delete", t, :method => :delete, :confirm => "Are you sure?" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No future treatments have been scheduled yet!</p>
<% end %>

<h3>Add Treatment</h3>
<%= semantic_form_for @treatment, :input_html => { :id => "treatment_form" } do |f| %>
  <%= f.inputs do %>
    <%= f.input :start_date, :as => :string, :input_html => { :datepicker => "true" } %>
    <%= f.input :end_date, :as => :string, :input_html => { :datepicker => "true" } %>
    <%= f.input :treatment_type, :collection => TreatmentType.names %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>








<% if false %>

  <h3>Latest Visit</h3>
  <% if @visit %>
    <p><%= @visit.description %> on <b><%= @visit.date %></b></p>
  <% else %>
    <p><%= @tb_patient.name %> has not visited yet!</p>
  <% end %>

  <h4>Check In</h4>
  <% if @tb_patient.checked_in? %>
    <p><%= @tb_patient.name %> has already checked in today!</p>
  <% end %>
  <%= form_tag check_in_patient_path(@tb_patient), :method => :post, :id => "check_in" do %>
    <%= text_field_tag :description, nil, :placeholder => "Description", :disabled => @tb_patient.checked_in? %>
    <%= submit_tag "Check in", :disabled => @tb_patient.checked_in? %>
  <% end %>

<% end %>