config/routes.rb
RemindavaxPilot::Application.routes.draw do

  match '/prepare_reminders', :to => 'patients#prepare_reminders', :via => :get
  match '/send_reminders', :to => 'patients#send_reminders', :via => :post

  resources :patients do
    collection do
      get 'autocomplete'
      get 'today'
    end
    member do
      post 'check_in'
      resources :appointments
    end
  end
  resources :tb_patients do
    member do
      resources :treatments
    end
  end
  resources :users
  resources :sessions
  resources :phcs do
    resources :subcenters, :only => [:new, :create, :index]
    collection do
      get 'summary'
    end
  end
  resources :anms
  resources :ashas
  resources :subcenters, :only => [:show, :destroy]

  root :to => redirect('/patients/today')
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/become_user', :to => 'sessions#become_user'
  match '/search', :to => 'patients#search'
  match '/search_tb', :to => 'tb_patients#search'

  post '/appointments/batch_update_dates'

  get '/cron/anm_sms'

  match '/summary', :to => 'phcs#summary'
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name, :husband_name, :mother_age, :subcenter_id, :village, :anm_id, :asha_id, :mobile, :cell_access,
    :taayi_card_number, :ec_number, :expected_delivery_date, :caste, :education, :delivery_place

  belongs_to :phc
  validates :phc, :presence => true
  belongs_to :subcenter
  validates :subcenter, :presence => true
  belongs_to :anm
  validates :anm, :presence => true
  belongs_to :asha
  has_many :visits, :dependent => :destroy
  has_many :appointments, :dependent => :destroy
  has_many :sms

  validates :name, :presence => true
  # No validation for husband name
  validates :mother_age, :presence => true, :numericality => true
  validates :village, :presence => true
  validates :mobile, :numericality => true, :if => Proc.new { |p| !p.mobile.blank? }
  validates_length_of :mobile, :is => 10 , :message => "should be 10 digits", :if => Proc.new { |p| !p.mobile.blank? }
  validates :cell_access, :presence => true
  enumerate :cell_access do
    value :name => 'yes'
    value :name => 'no'
  end
  validates :taayi_card_number, :numericality => true, :if => Proc.new{ |p| !p.taayi_card_number.blank? }
  validates_length_of :taayi_card_number, :is => 7, :if => Proc.new{ |p| !p.taayi_card_number.blank? }
  validates_uniqueness_of :encrypted_taayi_card_number, :if => Proc.new{ |p| !p.taayi_card_number.blank? }
  validates :ec_number, :presence => true, :numericality => true, :length => { :within => 2..3 }
  validates :expected_delivery_date, :presence => true, :format => { :with => /\A\d\d\-\d\d\-\d\d\d\d\Z/, :message => "Expected delivery date must be of the form DD-MM-YYYY" }
  validates :caste, :presence => true
  enumerate :caste do
    value :name => 'SC'
    value :name => 'ST'
    value :name => 'Other'
  end
  enumerate :education do
    value :name => 'Illiterate'
    value :name => 'Literate'
    value :name => 'Primary Education'
    value :name => 'High School'
    value :name => 'Degree'
    value :name => 'Other'
  end
  validates :delivery_place, :presence => true
  enumerate :delivery_place do
    value :name => 'PHC'
    value :name => 'CHC'
    value :name => 'Taluk Hospital'
    value :name => 'District Hospital'
    value :name => 'Private Hospital'
    value :name => 'Other'
  end

  # Note: attr_encrypted _must_ go after enumerate (active_enum) in order to
  # work.
  attr_encrypted :husband_name, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :mother_age, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :village, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :mobile, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :cell_access, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :taayi_card_number, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :ec_number, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :expected_delivery_date, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :caste, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :education, :key => APP_CONFIG['encrypt_key']
  attr_encrypted :delivery_place, :key => APP_CONFIG['encrypt_key']

  before_create :randomize_receiving_texts
  after_create :generate_appointments

  def self.search(phc, query)
    where('phc_id = ? AND name LIKE ?', phc, "%#{query}%")
  end

  def self.creation_stats_by_week(phc_id)
    select("COUNT(1) as count, YEARWEEK(created_at, 1) as yrwk, YEAR(created_at) as year, WEEK(created_at, 1) as week")
      .where('phc_id = ?', phc_id)
      .group("yrwk")
      .order("yrwk DESC")
  end

  def checked_in?
    latest_visit && latest_visit.date == Date.today
  end

  def latest_visit
    Visit.where("patient_id = ?", self).order("date DESC").first
  end

  def scheduled_appointments
    if latest_visit
      Appointment.where("patient_id = ? AND date > ?", self, latest_visit.date).order("date ASC")
    else
      appointments
    end
  end

  def next_appointment
    scheduled_appointments.first if not scheduled_appointments.nil?
  end

  def appointment_today?
    appointments.select {|a| a.date == Date.today }.any?
  end

  def sent_sms_today?
    sms.select{ |sms| sms.date == Date.today }.any?
  end

  private

  # Randomly put this patient into control or experimental group
  def randomize_receiving_texts
    self.receiving_texts = (rand(2) == 1)
    return true # Apparently things break if this method doesn't return true
  end

  # Array of [appointment_type_id, time interval from expected delivery date]
  AUTO_APPOINTMENTS = [[1, -6.months], [2, -3.months], [3, -1.month], [4, 0.days], [5, 6.weeks], [6, 10.weeks], [7, 14.weeks], [8, 10.months]]
  def generate_appointments
    AUTO_APPOINTMENTS.each do |a|
      date = Date.parse(expected_delivery_date) + a[1]
      if date > Date.today
        appointments.create!(:date => date, :appointment_type_id => a[0])
      end
    end
  end
end

# == Schema Information
#
# Table name: patients
#
#  id                               :integer(4)      not null, primary key
#  name                             :string(255)
#  encrypted_mobile                 :string(255)
#  encrypted_cell_access            :string(255)
#  phc_id                           :integer(4)
#  created_at                       :datetime
#  updated_at                       :datetime
#  receiving_texts                  :boolean(1)
#  encrypted_expected_delivery_date :string(255)
#  encrypted_husband_name           :string(255)
#  encrypted_caste                  :string(255)
#  encrypted_taayi_card_number      :string(255)
#  encrypted_mother_age             :string(255)
#  encrypted_education              :string(255)
#  encrypted_delivery_place         :string(255)
#  anm_id                           :integer(4)
#  encrypted_ec_number              :string(255)
#  encrypted_village                :string(255)
#  subcenter_id                     :integer(4)
#  asha_id                          :integer(4)
#

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authorize, :only => [:show, :edit, :update, :destroy, :check_in]

  def index
    @patients = current_user.phc.patients.order("name ASC").paginate(:page => params[:page])
  end

  def show
    @visit = @patient.latest_visit
    @appointments = @patient.scheduled_appointments.order("date ASC")
    @appointment = Appointment.new
  end

  def new
    @patient = Patient.new
  end

  def create
    @phc = current_user.phc
    @patient = @phc.patients.build(params[:patient])
    if @patient.save
      flash[:success] = "Created a new registration!"
      redirect_to @patient
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update_attributes(params[:patient])
      flash[:success] = 'Updated registration!'
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy if @patient
    flash[:success] = "Successfully deleted registration"
    flash[:success] += " #{@patient.name}" if @patient
    redirect_to patients_path
  end

  def search
    if params[:q] # A query was actually entered
      if /\A\d{7}\Z/ === params[:q] # Entered an Taayi Card Number (7 digits)
        @patient = Patient.find_by_taayi_card_number(params[:q])
        if @patient
          redirect_to @patient
        else
          @patient = Patient.new(:taayi_card_number => params[:q])
          render :new
        end
      else # Entered a name
        @patients = Patient.search(current_user.phc, params[:q]).order("name ASC").paginate(:page => params[:page])
        if @patients.any?
          render :index
        else
          @patient = Patient.new(:name => params[:q])
          render :new
        end
      end
    else # Just rerender the search page if nothing was entered
      render :search
    end
  end

  def check_in
    if not @patient.checked_in?
      @patient.visits.create!(:date => Date.today, :description => params[:description])
    end
    respond_to do |format|
      format.html { redirect_to @patient }
      format.js
    end
  end

  def autocomplete
    @patients = Patient.search(current_user.phc, params[:term]).order("name ASC").map(&:name)
    respond_to do |format|
      format.json { render :json => @patients }
    end
  end

  def today
    # Yesterday and today
    @appts_today = current_user.phc
      .find_appointments_by_date(:after => 2.days.ago.to_date, :before => Date.tomorrow)
      .order("date ASC")
    # More than 2 days ago
    @overdue_appts = current_user.phc
      .find_appointments_by_date(:before => 1.day.ago.to_date)
      .order("date ASC")
  end

  def prepare_reminders
    get_reminders
  end

  def send_reminders
    appts = Appointment.find(params[:appointments])
    appts.each do |a|
      send_reminder(a) unless a.patient.subcenter.control?
    end
    flash[:success] = "Successfully sent #{appts.length} reminders!"
    redirect_to patients_path
  end

  private
    def authorize
      @patient = Patient.find(params[:id])
      unless @patient && @patient.phc.id == current_user.phc.id
        flash[:error] = "You do not have access to this patient"
        redirect_to patients_path
      end
    end

    def get_reminders
      # Remind delivery appointments 2 weeks in advance
      @advance_reminders = current_user.phc.find_appointments_by_date(:date => 2.weeks.from_now.to_date).order("date ASC").select do |appt|
        appt.appointment_type.appointment_type_id == 4
      end
      @advance_reminders += current_user.phc.find_appointments_by_date(:date => 3.days.from_now.to_date).order("date ASC")
      @reminders = current_user.phc.find_appointments_by_date(:date => 1.day.from_now.to_date).order("date ASC")
      @alerts = current_user.phc.find_appointments_by_date(:before => 2.days.ago.to_date).order("date ASC")
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_appt_today.html.erb
  <tr>
    <td class="check-in" data-patient="<%= appt_today.patient.id %>" data-checked-in="<%= appt_today.patient.checked_in? %>"></td>
    <td><%= link_to appt_today.patient.name, appt_today.patient %></td>
    <td><%= appt_today.patient.taayi_card_number %></td>
    <td><%= (appt_today.patient.subcenter.nil?) ? (link_to "None (Assign?)", edit_patient_path(appt_today.patient) ) : (link_to appt_today.patient.subcenter.name, appt_today.patient.subcenter) %></td>
    <td><%= (appt_today.patient.anm.nil?) ? (link_to "None (Assign?)", edit_patient_path(appt_today.patient) ) : (link_to appt_today.patient.anm.name, appt_today.patient.anm) %></td>
    <td><%= appt_today.info %></td>
    <td><%= link_to "Edit", edit_patient_path(appt_today.patient) %></td>
    <td><%= link_to "Delete", appt_today.patient, :method => :delete, :confirm => "Are you sure you want to delete this registration?" %></td>
  </tr>

app/views/patients/_form.html.erb
<%= semantic_form_for @patient do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :husband_name %>
    <%= form.input :mother_age %>
    <%= form.input :subcenter, :collection => current_user.phc.subcenters.order("name ASC") %>
    <%= form.input :village %>
    <%= form.input :anm, :collection => current_user.phc.anms.order("name ASC") %>
    <%= form.input :asha, :collection => current_user.phc.ashas.order("name ASC") %>
    <%= form.input :mobile %>
    <%= form.input :cell_access, :as => :radio %>
    <%= form.semantic_errors :encrypted_taayi_card_number %>
    <%= form.input :taayi_card_number %>
    <%= form.input :ec_number, :label => 'EC Number' %>
    <%= form.input :expected_delivery_date, :as => :string, :input_html => { :datepicker => "true" } %>
    <%= form.input :caste %>
    <%= form.input :education %>
    <%= form.input :delivery_place %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button :label => (@patient.new_record?) ? 'Create Registration' : 'Update Registration' %>
  <% end %>
<% end %>

app/views/patients/_reminder.html.erb
<tr>
  <td><%= link_to reminder.patient.name, reminder.patient %></td>
  <td><%= (reminder.patient.subcenter.nil?) ? "None" : (link_to reminder.patient.subcenter.name, reminder.patient.subcenter) %></td>
  <td><%= reminder.patient.village %></td>
  <td><%= (reminder.patient.anm.nil?) ? "None" : (link_to reminder.patient.anm.name, reminder.patient.anm) %></td>
  <td><%= (reminder.patient.anm.nil?) ? "None" : (reminder.patient.anm.mobile) %></td>
  <td><%= reminder.name %></td>
  <td><%= text_field_tag "appt_#{reminder.id}", reminder.date_str, :datepicker => true, :updateable => true, :appt_id => reminder.id %></td>
  <td><%= ! reminder.patient.subcenter.control? %></td>
</tr>

app/views/patients/_search_form.html.erb
<%= form_tag search_path, :method => :get, :id => "search_form" do %>
  <%= text_field_tag :q, params[:q], :placeholder => "Mother Name or Taayi Card #", :autocomplete => "patient" %>
  <%= submit_tag "Search!", :name => nil %>
<% end %>

app/views/patients/check_in.js.erb
set_checked_in(<%= @patient.id %>, true);

app/views/patients/index.html.erb
<%= render :partial => 'search_form' %>
<h1>Registrations</h1>
<p class="subhead">If the registration you are looking for is not listed below, please add the registration <%= link_to "here", new_patient_path %>.</p>

<%= will_paginate %>

<table id="patients">
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Mobile</td>
      <td>Taayi Card Number</td>
      <td>Caste</td>
      <td>Next Appointment</td>
      <td>Latest Visit</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |p| %>
      <tr>
        <td><%= link_to p.name, p %></td>
        <td><%= (p.subcenter.nil?) ? "None" : (link_to p.subcenter.name, p.subcenter) %></td>
        <td><%= p.mobile %></td>
        <td><%= (p.taayi_card_number.nil?) ? "N/A" : p.taayi_card_number %></td>
        <td><%= Patient::Caste[p.caste.to_i] %></td>
        <td><%= (p.next_appointment.nil?) ? "None" : p.next_appointment.date %></td>
        <td><%= (p.latest_visit.nil?) ? "None" : p.latest_visit.date %></td>
        <td><%= link_to "Edit", edit_patient_path(p) %></td>
        <td><%= link_to "Delete", p, :method => :delete, :confirm => "Are you sure you want to delete this registration?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<%= link_to "Add New Registration to Database", new_patient_path, :id => "add_patient" %>

app/views/patients/new.html.erb
<h2>New Patient</h2>
<%= semantic_form_for @patient do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :husband_name %>
    <%= form.input :subcenter %>
    <%= form.input :mobile %>
    <%= form.input :cell_access, :as => :radio, :collection => ["yes", "no"] %>
    <%= form.input :taayi_card_number %>
    <%= form.input :expected_delivery_date, :as => :string, :input_html => { :datepicker => "true" } %>
    <%= form.input :caste, :as => :select, :collection => %w{SC ST Other} %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>

app/views/patients/prepare_reminders.html.erb
<h2>Advance Reminders</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
      <td>Appointment Date</td>
      <td>Receives Texts?</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @advance_reminders %>
  </tbody>
</table>

<h2>Reminders</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
      <td>Appointment Date</td>
      <td>Receives Texts?</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @reminders %>
  </tbody>
</table>

<h2>Alerts</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
      <td>Appointment Date</td>
      <td>Receives Texts?</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @alerts %>
  </tbody>
</table>

<%= form_tag send_reminders_path, :method => :post, :class => "left" do %>
  <% [@advance_reminders, @reminders, @alerts].flatten.each do |a| %>
    <%= hidden_field_tag "appointments[]", a.id %>
  <% end %>
  <%= submit_tag "Send SMS Reminders", :confirm => "Are you ready to send these SMS now?" %>
<% end %>

<button id="batch_update_dates" class="right">Save Changes</button>

app/views/patients/prepare_sms.html.erb
<h2>Advance Reminders</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @advance_reminders %>
  </tbody>
</table>

<h2>Reminders</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @reminders %>
  </tbody>
</table>

<h2>Alerts</h2>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Subcenter</td>
      <td>Village</td>
      <td>ANM Name</td>
      <td>ANM Mobile</td>
      <td>Appointment</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'reminder', :collection => @alerts %>
  </tbody>
</table>

app/views/patients/search.html.erb
<h1>Search</h1>
<p class="quiet">Please enter the name of your registration, or add a new registration <%= link_to "here", new_patient_path %></p>
<%= render :partial => 'search_form' %>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1>
<%= link_to "Edit", edit_patient_path(@patient) %>

<ul class="details">
  <li><b>Husband Name:</b> <%= @patient.husband_name %></li>
  <li><b>Mother Age:</b> <%= @patient.mother_age %></li>
  <li><b>Subcenter:</b> <%= (@patient.subcenter.nil?) ? "None" : (link_to @patient.subcenter.name, @patient.subcenter) %></li>
  <li><b>Village:</b> <%= @patient.village %></li>
  <li><b>ANM:</b> <%= (@patient.anm.nil?) ? (link_to "None (Assign?)", edit_patient_path(@patient) ): (link_to @patient.anm.name, @patient.anm) %></li>
  <li><b>ASHA:</b> <%= (@patient.asha.nil?) ? (link_to "None (Assign?)", edit_patient_path(@patient) ): (link_to @patient.asha.name, @patient.asha) %></li>
  <li><b>Mobile:</b> <%= @patient.mobile %></li>
  <li><b>Cell Access:</b> <%= @patient.cell_access %></li>
  <li><b>Taayi Card Number:</b> <%= (@patient.taayi_card_number.nil?) ? "N/A" : @patient.taayi_card_number %></li>
  <li><b>Expected Delivery Date:</b> <%= @patient.expected_delivery_date %></li>
  <li><b>Caste:</b> <%= Patient::Caste[@patient.caste.to_i] %></li>
  <li><b>Education:</b> <%= Patient::Education[@patient.education.to_i] %></li>
  <li><b>Delivery Place:</b> <%= Patient::DeliveryPlace[@patient.delivery_place.to_i] %></li>
  <li><b>Receives Texts: </b> <%= @patient.receiving_texts? %></li>
</ul>

<h3>Latest Visit</h3>
<% if @visit %>
  <p><%= @visit.description %> on <b><%= @visit.date %></b></p>
<% else %>
  <p><%= @patient.name %> has not visited yet!</p>
<% end %>

<h4>Check In</h4>
<% if @patient.checked_in? %>
  <p><%= @patient.name %> has already checked in today!</p>
<% end %>
<%= form_tag check_in_patient_path(@patient), :method => :post, :id => "check_in" do %>
  <%= text_field_tag :description, nil, :placeholder => "Description", :disabled => @patient.checked_in? %>
  <%= submit_tag "Check in", :disabled => @patient.checked_in? %>
<% end %>

<h3>Scheduled Appointments</h3>
<% if @appointments.any? %>
  <ul>
    <% @appointments.each do |appt| %>
      <li><%= appt.name %> on <b><%= appt.date %></b> | <%= link_to "Delete", appt, :method => :delete, :confirm => "Are you sure?" %></li>
    <% end %>
  </ul>
<% else %>
  <p>No appointment have been scheduled yet!</p>
<% end %>

<h3>Add Appointment</h3>
<%= semantic_form_for @appointment, :input_html => { :id => "appointment_form" } do |f| %>
  <%= f.inputs do %>
    <%= f.input :date, :as => :string, :input_html => { :datepicker => "true" } %>
    <%= f.input :appointment_type, :collection => AppointmentType.names %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/patients/today.html.erb
<h2>Cases for Today</h2>

<table>
  <thead>
    <tr>
      <td></td>
      <td>Name</td>
      <td>Taayi Card Number</td>
      <td>Subcenter</td>
      <td>ANM Name</td>
      <td>Next Appointment</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'appt_today', :collection => @appts_today %>
  </tbody>
</table>

<h2>Late Cases</h2>
<table>
  <thead>
    <tr>
      <td></td>
      <td>Name</td>
      <td>Taayi Card Number</td>
      <td>Subcenter</td>
      <td>ANM Name</td>
      <td>Next Appointment</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'appt_today', :collection => @overdue_appts %>
  </tbody>
</table>

<%= link_to "Prepare SMS!", prepare_reminders_path, :class => "big-link right" %>