config/routes.rb
RemindavaxPilot::Application.routes.draw do

  match '/prepare_reminders', :to => 'patients#prepare_reminders', :via => :get
  match '/send_reminders', :to => 'patients#send_reminders', :via => :post

  resources :patients do
    collection do
      get 'autocomplete'
      get 'today'
    end
    member do
      post 'check_in'
      resources :appointments
    end
  end
  resources :tb_patients do
    member do
      resources :treatments
    end
  end
  resources :users
  resources :sessions
  resources :phcs do
    resources :subcenters, :only => [:new, :create, :index]
    collection do
      get 'summary'
    end
  end
  resources :anms
  resources :ashas
  resources :subcenters, :only => [:show, :destroy]

  root :to => redirect('/patients/today')
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/become_user', :to => 'sessions#become_user'
  match '/search', :to => 'patients#search'
  match '/search_tb', :to => 'tb_patients#search'

  post '/appointments/batch_update_dates'

  get '/cron/anm_sms'

  match '/summary', :to => 'phcs#summary'
  

end

app/views/layouts/_header.html.erb
<header>
  <h1 id="logo" class="left">
    <%= link_to(root_path) do %>
      Reminda<span>vax</span>
    <% end %>
  </h1>
  <nav>
  <ul>
    <% if logged_in? %>
      <li>
      Welcome, <b><%= current_user.username %></b>
      <% if current_user.admin? %>
        | <%= link_to "Create User", new_user_path %> | <%= link_to "Create PHC", new_phc_path %>
      <% end %>
      | <%= link_to "Create ANM", new_anm_path %> | <%= link_to "Create ASHA", new_asha_path %>
      | <%= link_to "Create Registration", new_patient_path %>
      | <%= link_to "Create TB Registration", new_tb_patient_path %>
      </li>
      <li>PHC: <b><%= current_user.phc.name %></b>
      <% if current_user.admin? %>
        | <%= link_to "PHCs", phcs_path %>
      <% end %>
      | <%= link_to "ANMs", anms_path %>
      | <%= link_to "ASHAs", ashas_path %>
      | <%= link_to "all cases", patients_path %>
      | <%= link_to "all TB cases", tb_patients_path %>
      | <%= link_to "due today", today_patients_path %>
      | <%= link_to "search", search_path %>
      | <%= link_to "prepare sms", prepare_reminders_path %>
      </li>
      <li><%= link_to "logout", logout_path %></li>
    <% else %>
      <li><%= link_to "login", login_path %></li>
    <% end %>
  </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remindavax</title>
  <!--[if lt IE 9>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.9.custom' %>
  <%= stylesheet_link_tag 'formtastic' %>
  <%= stylesheet_link_tag 'formtastic_changes' %>
  <%= stylesheet_link_tag 'custom' %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'anms' %>
  <%= airbrake_javascript_notifier %>
  <%-# javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" %>
  <%-# javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="wrap" class="container">
    <%= render 'layouts/header' %>
    <section id="flash">
      <% flash.each do |key, value| %>
        <div class="<%= key %>"><%= value %></div>
      <% end %>
    </section>
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>